Repository MTES-MCT/monitorenv, pull requests merged in 2023-08, with the labels that each got.

#719 [Mission] Champ date de fin de mission obligatoire et amélioration du filtre période pour prendre en compte la date de fin
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt
  backend/src/main/resources/db/testdata/V666.6__insert_dummy_env_actions.sql
  frontend/cypress/e2e/00_side_window_missions.spec.ts
  frontend/cypress/e2e/01_side_window_mission.spec.ts
  frontend/cypress/e2e/02_side_window_mission_actions.spec.ts
  frontend/src/features/missions/MissionForm/Schemas/index.ts
Labels: feat. enhancement

#720 [Mission] Garder coché la case "dates et heures de surveillance équivalentes à celles de la mission" quand on revient sur une mission
  frontend/src/features/missions/MissionForm/MissionForm.tsx
Labels: bug

#705 [Snyk] Upgrade styled-components from 5.3.10 to 5.3.11
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#706 [Snyk] Upgrade redux-thunk from 2.4.1 to 2.4.2
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#704 [Snyk] Upgrade ramda from 0.28.0 to 0.29.0
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#727 [Reportings] Résolution du bug de tri du tableau par statut
  frontend/src/api/reportingsAPI.ts
  frontend/src/features/Reportings/ReportingsList/Columns/index.tsx
Labels: bug

#737 [Mission] Pouvoir cliquer n'importe où pour quitter la sélection des sous-thématiques
  frontend/src/features/Reportings/ReportingForm/ThemeSelector/SubThemesSelector.tsx
  frontend/src/features/Reportings/ReportingsList/Filters/index.tsx
  frontend/src/features/SideWindow/index.tsx
  frontend/src/features/SideWindow/style.ts
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ActionTargetSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/NatinfSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/RelevantCourtSelector.jsx
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ProtectedSpeciesSelector.tsx
  frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
  frontend/src/ui/NewWindow/NewWindowContext.ts
  frontend/src/ui/NewWindow/index.tsx
  frontend/src/ui/NewWindow/types.ts
  frontend/src/ui/NewWindow/useNewWindow.ts
Labels: bug

#743 [Mission] Sauvegarder la mission en cours à l'ajout d'une mission depuis la carte + ajout de l'unité dans l'entête d'une nouvelle mission
  frontend/src/domain/use_cases/missions/addMission.ts
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx
  frontend/src/utils/getMissionTitle.ts
Labels: bug

#753 [AMP] Scroller dans la liste de recherche des AMP à la sélection d'une AMP sur la carte
  frontend/src/domain/entities/layers/constants.ts
  frontend/src/domain/shared_slices/SelectedAmp.ts
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/index.tsx
  frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx
  frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts
  frontend/src/features/map/layers/AMP/index.ts
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
Labels: feat. enhancement

#736 [Mission] Affichage du tag "1 INF EN ATTENTE DE PV" dans la colonne résumé de la mission
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/ui/ControlInfractionsTags.tsx
Labels: feat. enhancement

#766 [Tech] Utilisation d'icônes de Monitor-ui + suppression d'un style global
  frontend/src/features/layersSelector/utils/LayerSelector.style.ts
  frontend/src/features/map/tools/measurements/MeasurementMapButton.tsx
  frontend/src/features/missions/MissionForm/Schemas/index.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/uiMonitor/icons/Measure_broken_line.svg
  frontend/src/uiMonitor/icons/Measure_circle.svg
Labels: bug

#756 [Regulatory] Amélioration de la recherches des zones règlementaires
  backend/src/main/resources/db/testdata/V666.2__insert_dummy_regulations_cacem.sql
  backend/src/main/resources/db/testdata/V666.8__dummy_amp_cacem.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaRegulatoryAreaRepositoryITests.kt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/layersSelector/base/index.tsx
  frontend/src/features/layersSelector/index.tsx
  frontend/src/features/layersSelector/regulatory/metadata/index.tsx
  frontend/src/features/layersSelector/search/LayerFilters.tsx
  frontend/src/features/layersSelector/search/index.tsx
  frontend/src/features/map/controls/MapCoordinatesBox.tsx
Labels: bug

#779 [Reportings] Corrections de style
  frontend/package-lock.json
  frontend/package.json
  frontend/src/domain/use_cases/reportings/duplicateReporting.ts
  frontend/src/features/Reportings/Filters/Table/index.tsx
  frontend/src/features/Reportings/ReportingsList/Cells/ButtonsRowGroup.tsx
  frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx
  frontend/src/features/layersSelector/search/LayerFilters.tsx
  frontend/src/ui/ControlInfractionsTags.tsx
Labels: bug

#778 [Missions] Résolution du bug d'enregistrement d'une mission
  frontend/cypress.config.ts
  frontend/cypress/e2e/03_side_window_missions_navigation.spec.ts
  frontend/cypress/e2e/04_create_reporting.spec.ts
  frontend/cypress/e2e/05_reportings.spec.ts
  frontend/src/domain/shared_slices/MissionsState.ts
  frontend/src/domain/shared_slices/ReportingState.ts
  frontend/src/domain/use_cases/navigation/deleteTab.ts
  frontend/src/features/SideWindow/SideWindowLauncher.tsx
  frontend/src/features/missions/MissionForm/modals/CancelEditModal.tsx
  frontend/src/features/missions/MissionsNavBar.tsx
Labels: bug

#787 [Reporting] Ajout d'un type de cible "Autre" et résolution du bug sur les filtres de façade
  backend/pom.xml
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/reporting/TargetTypeEnum.kt
  backend/src/main/resources/db/migration/internal/V0.094__update_reportings_target_types.sql
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/entities/seaFrontType.ts
  frontend/src/domain/entities/targetType.ts
  frontend/src/features/Reportings/Filters/index.tsx
  frontend/src/features/Reportings/ReportingForm/Target/TargetDetails.tsx
  frontend/src/features/Reportings/ReportingForm/Target/index.tsx
  frontend/src/features/Reportings/utils.ts
  frontend/src/features/commonComponents/TargetSelector/index.tsx
  frontend/src/features/map/overlays/actions/ControlCard.tsx
  frontend/src/features/missions/MissionForm/ActionCard.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ActionTargetSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
  infra/configurations/backend/application-dev.properties
Labels: bug, feat. enhancement

#795 [Reporting] Suppression de la notion d'avéré / non avéré et ajout d'un trigramme
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/reporting/ReportingEntity.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/GetReportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/CreateOrUpdateReportingDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/ReportingDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/ReportingDetailedDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsController.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt
  backend/src/main/resources/db/migration/internal/V0.095__update_reportings_table.sql
  backend/src/main/resources/db/testdata/V666.11__insert_dummy_reportings.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateReportingUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsControllerITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingITests.kt
  frontend/src/api/reportingsAPI.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/shared_slices/ReportingsFilters.ts
  frontend/src/features/Reportings/Filters/Table/index.tsx
  frontend/src/features/Reportings/Filters/index.tsx
  frontend/src/features/Reportings/ReportingForm/ReportingForm.tsx
  frontend/src/features/Reportings/ReportingForm/Schema/index.tsx
  frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
  frontend/src/features/Reportings/style.ts
  frontend/src/features/map/layers/Reportings/reportingsGeometryHelpers.ts
Labels: feat. enhancement

#789 [Mission] Point de contrôle obligatoire à la fermeture d'une mission, résolution du bug du bouton "Réinitialiser" sur la modal d'édition d'une zone ou d'une point
  frontend/src/domain/shared_slices/Draw.ts
  frontend/src/domain/use_cases/draw/drawGeometry.ts
  frontend/src/features/Reportings/ReportingForm/Position/PointPicker.tsx
  frontend/src/features/Reportings/ReportingForm/Position/ZonePicker.tsx
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/features/missions/MissionForm/Schemas/Control.ts
  frontend/src/features/missions/MultiPointPicker.tsx
Labels: bug

#798 [Tech] homogénisation des déclarations de variable
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/AMPModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/AdministrationModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlResourceModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlThemeModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/DepartmentsAreasModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/EnvActionModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/FacadeAreasModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionControlResourceModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionControlUnitModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/NatinfModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/RegulatoryAreaModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/SemaphoreModel.kt
Labels: tech. enhancement
