Repository MTES-MCT/monitorenv, pull requests merged in 2023-07, with the labels that each got.

#632 [Mission] Résolution du problème de largeur de la sideWindow
  frontend/src/features/SideWindow/index.tsx
  frontend/src/features/missions/MissionForm/index.tsx
Labels: bug

#615 [Missions] Ajout d'onglets pour pouvoir éditer/créer plusieurs missions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/domain/entities/missions.ts
  frontend/src/domain/entities/sideWindow.js
  frontend/src/domain/shared_slices/MissionsState.ts
  frontend/src/domain/shared_slices/MultiMissions.ts
  frontend/src/domain/shared_slices/index.js
  frontend/src/domain/use_cases/missions/addMission.ts
  frontend/src/domain/use_cases/missions/createOrEditMission.ts
  frontend/src/domain/use_cases/missions/deleteMission.ts
  frontend/src/domain/use_cases/missions/editMission.js
  frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/domain/use_cases/navigation/deleteTab.ts
  frontend/src/domain/use_cases/navigation/onNavigateBetweenMapAndSideWindow.ts
  frontend/src/domain/use_cases/navigation/switchTab.ts
  frontend/src/features/SideWindow/Route.ts
  frontend/src/features/SideWindow/SideWindowLauncher.tsx
  frontend/src/features/SideWindow/index.tsx
  frontend/src/features/SideWindow/slice.ts
  frontend/src/features/SideWindow/style.ts
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/features/map/overlays/missions/MissionCard.tsx
  frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/features/missions/MissionsList/CellEditMission.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
  frontend/src/features/missions/MissionsList/index.tsx
  frontend/src/features/missions/MissionsMenu.tsx
  frontend/src/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/ui/MissionStatusLabel.tsx
  frontend/src/ui/MissionStatusTag.tsx
  frontend/src/utils/getIdTyped.ts
  frontend/src/utils/getMissionPageRoute.ts
  frontend/src/utils/getMissionTitle.ts
  frontend/src/utils/isNewMission.ts
Labels: new feature

#633 [Tech] envoi des sourcemaps à sentry
  .github/workflows/cicd-app.yml
  Makefile
  frontend/src/index.tsx
  infra/docker/app/Dockerfile
Labels: tech. enhancement

#639 [Mission] Accès à l'édition complète de la mission même si elle est clôturée, résolution du bug de suppression des unités multiples
  frontend/src/features/coordinates/DDCoordinatesInput.tsx
  frontend/src/features/coordinates/DMDCoordinatesInput.tsx
  frontend/src/features/coordinates/DMSCoordinatesInput.tsx
  frontend/src/features/map/tools/interest_points/EditInterestPoint.tsx
  frontend/src/features/missions/MissionForm/ActionCard.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ActionForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx
  frontend/src/features/missions/MissionForm/ActionsForm.tsx
  frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx
  frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/Schemas/index.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/MultiPointPicker.tsx
  frontend/src/features/missions/MultiZonePicker.tsx
Labels: bug

#638 [Mission] Possibilité de n'ajouter qu'un contact en cas de mission conjointe avec plusieurs unités
  frontend/src/features/missions/MissionForm/Schemas/index.ts
Labels: feat. enhancement

#640 [Missions] Validation des géométries de zone de mission et de surveillance
  frontend/package-lock.json
  frontend/package.json
  frontend/src/domain/shared_slices/Draw.ts
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/utils/geometryValidation.ts
Labels: feat. enhancement

#641 [Missions] ne pas bloquer l'enregistrement si le champ `theme` est null
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/missions/ThemeEntity.kt
  backend/src/main/resources/db/testdata/V666.6__insert_dummy_env_actions.sql
  frontend/cypress/e2e/02_side_window_mission_actions.spec.ts
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ActionTheme.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/MultipleThemeElement.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ProtectedSpeciesSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/SubThemesSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/useCleanSubThemesOnThemeChange.tsx
  frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/features/missions/MissionsList/CellActionThemes.tsx
  frontend/src/utils/extractThemesAsText.ts
Labels: bug

#631 [Snyk] Upgrade org.http4k:http4k-client-apache from 4.43.0.0 to 4.45.0.0
  backend/pom.xml
Labels: dependencies

#692 [REG/AMP] amélioration de la recherche des couches
  frontend/src/features/layersSelector/search/index.tsx
Labels: bug
