Repository MTES-MCT/monitorenv, pull requests merged in 2023-11, with the labels that each got.

#923 [Mission] Amélioration de la recherche des unités et résolution du bug à la sélection du type de cible
  frontend/cypress/e2e/side_window/mission_list/filters.spec.ts
  frontend/cypress/e2e/side_window/mission_list/missions.spec.ts
  frontend/cypress/e2e/side_window/reporting/filters.spec.ts
  frontend/cypress/e2e/side_window/reporting/reportings.spec.ts
  frontend/src/api/missionsAPI.ts
  frontend/src/api/reportingsAPI.ts
  frontend/src/domain/entities/missions.ts
  frontend/src/domain/shared_slices/MissionFilters.ts
  frontend/src/domain/shared_slices/ReportingsFilters.ts
  frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedAdministrationNames.ts
  frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedControlUnitIds.ts
  frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedThemes.ts
  frontend/src/domain/use_cases/reporting/filters/sourceFilterFunction.ts
  frontend/src/domain/use_cases/reporting/filters/subThemesFilterFunction.ts
  frontend/src/domain/use_cases/reporting/filters/themeFilterFunction.ts
  frontend/src/features/Reportings/Filters/Map/index.tsx
  frontend/src/features/Reportings/Filters/Table/FilterTags.tsx
  frontend/src/features/Reportings/Filters/Table/index.tsx
  frontend/src/features/Reportings/Filters/index.tsx
  frontend/src/features/Reportings/Filters/style.ts
  frontend/src/features/layersSelector/search/LayerFilters.tsx
  frontend/src/features/layersSelector/search/index.tsx
  frontend/src/features/missions/MissionsList/Filters/FilterTags.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
  frontend/src/hooks/useGetFilteredMissionsQuery.ts
Labels: feat. enhancement

#954 [Unités] Amélioration de la recherche des unités depuis une mission
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/layersSelector/search/index.tsx
  frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
Labels: feat. enhancement

#961 [Carte] Résolution des conflits avec la ligne pointillée des sémaphores + ajout des cette ligne sur les bases et signalements
  frontend/src/domain/shared_slices/Global.ts
  frontend/src/features/Station/components/StationLayer/index.ts
  frontend/src/features/Station/components/StationLayer/utils.ts
  frontend/src/features/map/layers/Reportings/EditingReportingLayer.tsx
  frontend/src/features/map/layers/Reportings/SelectedReporting.tsx
  frontend/src/features/map/layers/Reportings/index.tsx
  frontend/src/features/map/layers/Reportings/style.ts
  frontend/src/features/map/layers/Semaphores/index.ts
  frontend/src/features/map/layers/Semaphores/style.ts
  frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
  frontend/src/features/map/overlays/semaphores/SemaphoreCard.tsx
Labels: bug

#963 [Tech] Change la fréquence des updates Dependabot au mensuel
  .github/dependabot.yml
Labels: WAITING FOR REVIEW

#987 [Tech] Revert "[Missions] Rafraichissement automatique (#951)"
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/events/UpdateMissionEvent.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsController.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/SSEMissionController.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateMissionUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsControllerITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsControllerITests.kt
  backend/src/test/resources/application.properties
  frontend/cypress/e2e/side_window/mission/mission.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/missionsAPI.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/libs/ReconnectingEventSource.ts
  frontend/src/libs/ReconnectingEventSourceError.ts
  frontend/src/libs/ReconnectingEventSourceInit.ts
  infra/configurations/backend/application-dev.properties
Labels: bug

#968 [Unités] Retouches diverses sur le backoffice et la fiche unité
  frontend/package-lock.json
  frontend/package.json
  frontend/src/domain/entities/controlUnit.ts
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/FormikNameSelect.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/constants.ts
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/utils.ts
  frontend/src/utils/__tests__/sortCollectionByLocalizedProps.test.ts
  frontend/src/utils/sortCollectionByLocalizedProps.ts
Labels: bug

#969 [Missions] Impossible de modifier les unités ou moyens des anciennes missions lorsqu'il y a au moins un moyen rattaché (bis)
  backend/src/main/resources/db/migration/internal/V0.102__fix_mission_control_resources_id_sequence.sql
Labels: bug

#970 [Unités] Fixe plusieurs bugs concernant l'affichage des bases sur la carte
  frontend/cypress/e2e/main_window/station_overlay.spec.ts
  frontend/public/icons/station-layer-icon.svg
  frontend/src/components/OverlayCard.tsx
  frontend/src/domain/entities/layers/constants.ts
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/index.tsx
  frontend/src/features/Station/components/StationLayer/index.ts
  frontend/src/features/Station/components/StationLayer/utils.ts
  frontend/src/features/Station/components/StationOverlay/StationCard/Item.tsx
  frontend/src/features/Station/components/StationOverlay/StationCard/index.tsx
  frontend/src/features/Station/components/StationOverlay/constants.ts
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
Labels: bug

#991 [ZonesRéglementaires] Résolution du bug au clique sur une zone réglementaire (sur la carte)
  frontend/src/features/layersSelector/search/LayerFilters.tsx
  frontend/src/features/map/BaseMap.tsx
  frontend/src/store/index.ts
  frontend/src/store/reducers.ts
Labels: bug

#993 [Zones] Résolution du bug d'affichage de la carte (superposition d'éléments)
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx
  frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx
Labels: bug

#998 [Mission] Invalidation du cache
  frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts
  frontend/src/domain/use_cases/reporting/duplicateReporting.ts
  frontend/src/domain/use_cases/reporting/editReportingInLocalStore.ts
Labels: bug

#999 [Unité] Amélioration de la recherche des unités (vue liste et fiche mission)
  frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
Labels: bug

#965 [Tech] Migre Node de v18 vers v20
  .github/workflows/cicd-app.yml
  Makefile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/APIWorker.ts
  frontend/src/features/Reportings/ReportingForm/FormComponents/Source.tsx
  frontend/src/features/layersSelector/search/index.tsx
  frontend/src/features/map/controls/MapCoordinatesBox.tsx
  frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts
  frontend/src/features/map/layers/InterestPointLayer.tsx
  frontend/src/features/map/layers/MapLayer.tsx
  frontend/src/features/map/layers/MeasurementLayer.tsx
  frontend/src/features/map/layers/Regulatory/RegulatoryPreviewLayer.ts
  frontend/src/features/map/overlays/InterestPointOverlay.js
  frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
  infra/docker/app/Dockerfile
Labels: tech. enhancement, WAITING FOR REVIEW

#1006 [Signalements] Différentes corrections sur le rattachement d'un signalement à une mission
  frontend/package-lock.json
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/features/MainWindow/components/RightMenu/ButtonWrapper.tsx
  frontend/src/features/MainWindow/components/RightMenu/ControlUnitListButton.tsx
  frontend/src/features/Reportings/Layers/MissionToAttach/index.tsx
  frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/ReportingsButton/index.tsx
  frontend/src/features/Semaphores/SearchSemaphoreButton/index.tsx
  frontend/src/features/Station/components/StationLayer/index.ts
  frontend/src/features/Station/components/StationOverlay/StationCard/index.tsx
  frontend/src/features/map/layers/Reportings/EditingReportingLayer.tsx
  frontend/src/features/map/layers/Semaphores/index.ts
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
  frontend/src/features/map/overlays/semaphores/SemaphoreCard.tsx
  frontend/src/features/map/tools/interestPoint/InterestPointMapButton.tsx
  frontend/src/features/map/tools/measurements/MeasurementMapButton.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx
  frontend/src/features/missions/MissionForm/AttachReporting/index.tsx
  frontend/src/features/missions/MissionsButton/index.tsx
Labels: bug

#1008 [Mission] Résolution du souci de cache en cas de détachement d'un signalement depuis une mission
  frontend/src/api/missionsAPI.ts
  frontend/src/domain/entities/missions.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/domain/use_cases/reporting/attachMission.ts
  frontend/src/domain/use_cases/reporting/closeReporting.ts
  frontend/src/domain/use_cases/reporting/duplicateReporting.ts
  frontend/src/domain/use_cases/reporting/editReportingInLocalStore.ts
  frontend/src/domain/use_cases/reporting/switchReporting.ts
  frontend/src/domain/use_cases/reporting/unattachMissionFromReporting.ts
  frontend/src/features/Reportings/ReportingForm/AttachMission/AttachMissionToReportingModal.tsx
  frontend/src/features/Reportings/ReportingForm/index.tsx
  frontend/src/features/Reportings/slice.ts
  frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx
  frontend/src/features/missions/Missions.helpers.ts
Labels: bug
