Repository MTES-MCT/monitorenv, pull requests merged in 2023-10, with the labels that each got.

#869 [Measurement] Amélioration de l'outil de tracé de cercle
  frontend/src/features/map/tools/measurements/CustomCircleRange.tsx
Labels: feat. enhancement

#868 [Mission] Mise à jour des tags "Infractions"
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/ui/ControlInfractionsTags.tsx
Labels: feat. enhancement

#873 [Mission] Résolution du bug sur les thématiques et ajout de tests
  frontend/config/cypress.config.ts
  frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/mission/close_mission_validation.spec.ts
  frontend/cypress/e2e/side_window/mission/create_mission.spec.ts
  frontend/cypress/e2e/side_window/mission/mission_actions.spec.ts
  frontend/cypress/e2e/side_window/mission/mission_dates_validation.spec.ts
  frontend/cypress/e2e/side_window/mission_list/missions.spec.ts
  frontend/cypress/e2e/side_window/mission_list/missions_navigation.spec.ts
  frontend/cypress/e2e/side_window/reporting/reportings.spec.ts
  frontend/src/domain/entities/missions.ts
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/index.tsx
  frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/Schemas/Control.ts
  frontend/src/features/missions/MissionForm/Schemas/Surveillance.ts
  frontend/src/features/missions/MissionForm/Schemas/Theme.ts
  frontend/src/features/missions/MissionForm/Schemas/index.ts
  frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/features/missions/MultiPointPicker.tsx
  frontend/src/features/missions/MultiZonePicker.tsx
Labels: bug

#893 Import des données de modalités de contact et de zones d'intervention des unités
  .gitignore
  datascience/src/pipeline/data/dummy_area_notes.csv
  datascience/src/pipeline/data/dummy_terms_notes.csv
  datascience/src/pipeline/flows/control_resources_bases_contacts.py
  datascience/tests/test_pipeline/test_flows/test_control_resources_bases_contacts.py
Labels: new feature, data

#891 [OutilDeMesure] Bouton de validation pour tracé un cercle inactif si les deux champs ne sont pas remplis
  backend/src/main/resources/db/testdata/V666.5__insert_dummy_missions.sql
  frontend/cypress/e2e/side_window/mission/close_mission_validation.spec.ts
  frontend/cypress/e2e/side_window/mission/create_mission.spec.ts
  frontend/cypress/e2e/side_window/mission/mission_actions.spec.ts
  frontend/cypress/e2e/side_window/mission/mission_dates_validation.spec.ts
  frontend/src/features/map/tools/measurements/CustomCircleRange.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/Missions.helpers.ts
Labels: bug

#910 [Mission] Résolution d'un bug à l'enregistrement d'une mission
  frontend/cypress/e2e/side_window/mission/create_mission.spec.ts
  frontend/src/features/missions/MissionForm/MissionForm.tsx
Labels: bug

#928 [Mission] Résolution du bug à l'enregistrement d'une mission clôturée
  frontend/cypress/e2e/side_window/mission/mission.spec.ts
  frontend/src/features/missions/MissionForm/MissionForm.tsx
Labels: bug
