Repository MTES-MCT/monitorenv, pull requests merged in 2024-11, with the labels that each got.

#1851 [Tech] Supprime Ivan des assigné.es dans la config Dependabot
  .github/dependabot.yml
Labels: tech. enhancement

#1861 [Tech] Migrer le Frontend vers l'ESM
  frontend/.eslintrc.cjs
  frontend/config/fileTransformer.js
  frontend/config/jest.config.js
  frontend/config/jest.global.js
  frontend/config/multi-windows/jest.config.js
  frontend/package.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: tech. enhancement

#1871 [Brief]: Ajout de marge autour de la section commentaire
  frontend/src/features/Dashboard/components/Pdf/Brief.tsx
Labels: UI

#1888 [Zone de vigilance] Afficher la fenêtre de confirmation si on édite une ZV depuis la vue liste et qu'une autre est en cours d'édition
  frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/EditCell.tsx
Labels: bug, Zone de vigilance
