Repository MTES-MCT/monitorenv, pull requests merged in 2024-10, with the labels that each got.

#1755 [Tableau de bord & Brief] Résolution du bug du tooltip et des filtres des Unités
  frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/TerritorialPressure/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/index.tsx
Labels: bug, Tableau de bord et brief

#1772 [Sentry]: Désactivation de Sentry
  .github/workflows/cicd-app.yml
Labels: bug

#1800 [Tableau de bord]: ne pas filtrer les objets épinglés par rapport à la zone
  frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx
  frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx
  frontend/src/features/Dashboard/slice.ts
  frontend/src/features/Dashboard/useCases/editDashboard.ts
  frontend/src/features/Dashboard/useCases/editDashboardArea.ts
  frontend/src/features/Dashboard/utils.ts
Labels: Tableau de bord et brief

#1803 [Zone de vigilance] Ajout de la facade
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/vigilanceArea/VigilanceAreaEntity.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceArea.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/vigilanceArea/VigilanceAreaDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/vigilanceArea/VigilanceAreaDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/vigilanceArea/VigilanceAreasDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/VigilanceAreaModel.kt
  backend/src/main/resources/db/migration/internal/V0.156__add_column_sea_front_to_vigilance_area.sql
  backend/src/main/resources/db/testdata/V666.19__add_column_sea_front_to_vigilance_area.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceAreaUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/VigilanceAreasITests.kt
  frontend/src/features/Dashboard/types.ts
Labels: feat. enhancement
