Repository MTES-MCT/monitorenv, pull requests merged in 2024-01, with the labels that each got.

#1051 [Signalement] Ajout du champ date
  frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts
  frontend/src/App.tsx
  frontend/src/domain/entities/reporting.ts
  frontend/src/features/Reportings/ReportingForm/FormComponents/Footer.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/ReportingForm/Schema/index.tsx
  frontend/src/features/Reportings/ReportingForm/formikUseCases/updateReportingThemes.ts
  frontend/src/features/Reportings/style.ts
  frontend/src/features/SideWindow/index.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/Validity.tsx
  frontend/src/typings/index.d.ts
Labels: feat. enhancement

#1095 [Reporting] Résolution du bug d'enregistrement d'un signalement
  backend/src/main/resources/db/migration/internal/V0.107__update_reportings_sequence.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt.kt
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
Labels: bug

#1072 [Mission] Refacto du multi-missions
  frontend/src/domain/entities/missions.ts
  frontend/src/domain/shared_slices/MissionsState.ts
  frontend/src/domain/shared_slices/MultiMissions.ts
  frontend/src/domain/use_cases/map/updateMapInteractionListeners.ts
  frontend/src/domain/use_cases/missions/addMission.ts
  frontend/src/domain/use_cases/missions/attachReportingFromMap.ts
  frontend/src/domain/use_cases/missions/deleteMission.ts
  frontend/src/domain/use_cases/missions/deleteTab.ts
  frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/domain/use_cases/missions/saveMissionInLocalStore.ts
  frontend/src/domain/use_cases/missions/selectMissionOnMap.js
  frontend/src/domain/use_cases/missions/switchTab.ts
  frontend/src/features/Reportings/ReportingsButton/SearchReportings.tsx
  frontend/src/features/SideWindow/SideWindowLauncher.tsx
  frontend/src/features/map/layers/Missions/EditingMissionLayer.ts
  frontend/src/features/map/layers/Missions/SelectedMissionLayer.ts
  frontend/src/features/map/layers/Missions/index.tsx
  frontend/src/features/map/layers/Missions/missionGeometryHelpers.ts
  frontend/src/features/map/layers/Reportings/index.tsx
  frontend/src/features/map/overlays/missions/MissionCard.tsx
  frontend/src/features/map/overlays/missions/index.tsx
  frontend/src/features/missions/MissionForm/ActionCards/ReportingCard.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx
  frontend/src/features/missions/MissionForm/AttachReporting/AttachReportingToMissionModal.tsx
  frontend/src/features/missions/MissionForm/AttachReporting/index.tsx
  frontend/src/features/missions/MissionForm/AttachReporting/slice.ts
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/features/missions/MissionForm/hooks/useUpdateOtherControlTypes.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/MissionForm/slice.ts
  frontend/src/features/missions/Missions.helpers.ts
  frontend/src/features/missions/MissionsButton/index.tsx
  frontend/src/features/missions/MissionsNavBar.tsx
  frontend/src/features/missions/slice.ts
  frontend/src/features/missions/utils.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/store/reducers.ts
  frontend/src/utils/getMissionTitle.ts
Labels: tech. enhancement

#1099 [Reporting] Résolution du bug empêchant de rattacher plusieurs signalements à une mission
  frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts
  frontend/cypress/e2e/side_window/mission_form/close_mission_validation.spec.ts
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts
  frontend/src/domain/use_cases/reporting/unattachMissionFromReporting.ts
  frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/features/map/layers/Reportings/index.tsx
Labels: bug

#1103 [Unités] Fixe plusieurs glitchs sur la fiche unité
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/FormikNameSelect.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/shared/TextareaForm.tsx
Labels: bug

#1111 [Unités] Pouvoir créer une mission à partir d'une unité
  frontend/src/domain/use_cases/missions/addMission.ts
  frontend/src/domain/use_cases/reporting/createMissionFromReporting.ts
  frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx
Labels: feat. enhancement

#1110 [Unités] Fixe quelques glitchs sur les bases
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Placeholder.tsx
  frontend/src/features/Station/components/StationLayer/utils.ts
  frontend/src/features/Station/components/StationOverlay/index.tsx
  frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
  frontend/src/features/map/overlays/actions/index.tsx
  frontend/src/features/missions/Overlays/ReportingToAttach/index.tsx
Labels: bug

#1104 [Signalements] Ajout de la cible dans la vue liste des signalements
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/GetReportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/Reportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt
  backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts
  frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/reporting/filters.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/reportingsAPI.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/shared_slices/ReportingsFilters.ts
  frontend/src/features/Reportings/Filters/Map/index.tsx
  frontend/src/features/Reportings/Filters/Table/FilterTags.tsx
  frontend/src/features/Reportings/Filters/Table/index.tsx
  frontend/src/features/Reportings/Filters/index.tsx
  frontend/src/features/Reportings/Filters/style.ts
  frontend/src/features/Reportings/ReportingForm/Schema/index.tsx
  frontend/src/features/Reportings/ReportingsList/Cells/CellTarget.tsx
  frontend/src/features/Reportings/ReportingsList/Columns/index.tsx
  frontend/src/features/Reportings/components/LinkToMissionTag.tsx
  frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
  frontend/src/features/Reportings/utils.test.ts
  frontend/src/features/Reportings/utils.tsx
  frontend/src/utils/getQueryStringFormatted.ts
Labels: feat. enhancement

#1080 [Thématiques] Traitement des retours design
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/package-lock.json
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ActionTheme.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/MultipleThemeElement.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/TagsSelector.tsx
  frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx
  frontend/src/hooks/useGetControlPlans.ts
  frontend/src/hooks/useGetControlPlansByYear.ts
  frontend/src/utils/sortControlPlans.ts
Labels: feat. enhancement

#1117 [Tech] Amélioration de l'accès aux données des reducers
  frontend/src/api/regulatoryLayersAPI.ts
  frontend/src/components/ToastNotification.tsx
  frontend/src/domain/shared_slices/Regulatory.ts
  frontend/src/domain/use_cases/regulatory/closeRegulatoryZoneMetadata.js
  frontend/src/domain/use_cases/regulatory/loadRegulatoryData.js
  frontend/src/domain/use_cases/regulatory/loadRegulatoryData.ts
  frontend/src/domain/use_cases/regulatory/removeRegulatoryZoneFromMySelection.js
  frontend/src/domain/use_cases/regulatory/showRegulatoryZoneMetadata.js
  frontend/src/features/LocateOnMap/index.tsx
  frontend/src/features/MainWindow/components/RightMenu/ControlUnitListButton.tsx
  frontend/src/features/Reportings/Overlays/MissionToAttach/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Position/PointPicker.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Position/ZonePicker.tsx
  frontend/src/features/Semaphores/SearchSemaphoreButton/SearchSemaphores.tsx
  frontend/src/features/Semaphores/SearchSemaphoreButton/index.tsx
  frontend/src/features/SideWindow/Route.ts
  frontend/src/features/layersSelector/administrative/index.tsx
  frontend/src/features/layersSelector/amp/AMPLayersList.tsx
  frontend/src/features/layersSelector/amp/index.tsx
  frontend/src/features/layersSelector/base/index.tsx
  frontend/src/features/layersSelector/index.tsx
  frontend/src/features/layersSelector/regulatory/menu/RegulatoryLayerGroup.tsx
  frontend/src/features/layersSelector/regulatory/menu/RegulatoryLayerZone.tsx
  frontend/src/features/layersSelector/regulatory/menu/index.tsx
  frontend/src/features/layersSelector/regulatory/metadata/index.tsx
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/index.tsx
  frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx
  frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/index.tsx
  frontend/src/features/layersSelector/search/ResultsList/index.tsx
  frontend/src/features/layersSelector/search/index.tsx
  frontend/src/features/map/BaseMap.tsx
  frontend/src/features/map/MapExtentController.ts
  frontend/src/features/map/ShowRegulatoryMetadata.ts
  frontend/src/features/map/controls/MapCoordinatesBox.tsx
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts
  frontend/src/features/map/layers/AMP/index.ts
  frontend/src/features/map/layers/AdministrativeLayers.ts
  frontend/src/features/map/layers/DrawLayer.ts
  frontend/src/features/map/layers/MeasurementLayer.tsx
  frontend/src/features/map/layers/Regulatory/RegulatoryPreviewLayer.ts
  frontend/src/features/map/layers/Regulatory/index.ts
  frontend/src/features/map/layers/Reportings/SelectedReporting.tsx
  frontend/src/features/map/layers/Reportings/index.tsx
  frontend/src/features/map/overlays/MeasurementOverlay.tsx
  frontend/src/features/map/overlays/missions/index.tsx
  frontend/src/features/map/overlays/semaphores/index.tsx
  frontend/src/features/map/shared/RightMenuOnHoverArea.tsx
  frontend/src/features/map/tools/interestPoint/InterestPointMapButton.tsx
  frontend/src/features/map/tools/measurements/MeasurementMapButton.tsx
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx
  frontend/src/features/missions/MissionsButton/index.tsx
  frontend/src/features/missions/MultiPointPicker.tsx
  frontend/src/features/missions/MultiZonePicker.tsx
  frontend/src/features/missions/Overlays/ReportingToAttach/index.tsx
  frontend/src/hooks/useListenForDrawing.ts
  frontend/src/pages/HomePage.tsx
Labels: bug

#1039 [Tests] Ajout de tests e2e
  frontend/cypress/e2e/main_window/interest_point.spec.ts
  frontend/cypress/e2e/main_window/zones/__image_snapshots__/Main Window  AMP Layers  An AMP Should be searched, added to My Zones and showed on the map with the Zone button #0.png
  frontend/cypress/e2e/main_window/zones/amp_layers.spec.ts
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/src/App.tsx
  frontend/src/features/layersSelector/amp/AMPLayersList.tsx
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx
  frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/index.tsx
  frontend/src/features/layersSelector/search/ResultsList/index.tsx
  frontend/src/features/layersSelector/search/SearchInput.tsx
  frontend/src/features/layersSelector/utils/LayerSelector.style.ts
Labels: tech. enhancement

#1114 [Signalement] Ajout d'un champ de recherche (pour les cibles) dans la vue liste des signalements
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/GetReportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/Reportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt
  backend/src/main/resources/db/migration/internal/V0.110__create_reportings_fts_dictionnary.sql
  backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/src/api/reportingsAPI.ts
  frontend/src/domain/shared_slices/ReportingsFilters.ts
  frontend/src/features/Reportings/Filters/Map/index.tsx
  frontend/src/features/Reportings/Filters/ReportingSearch.tsx
  frontend/src/features/Reportings/Filters/Table/index.tsx
  frontend/src/features/Reportings/Filters/style.ts
  frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
  frontend/src/features/layersSelector/search/SearchInput.tsx
  frontend/src/features/layersSelector/search/index.tsx
Labels: feat. enhancement

#1134 [Signalements] Plusieurs améliorations design
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt
  backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql
  frontend/cypress/e2e/side_window/reporting/filters.spec.ts
  frontend/src/features/Reportings/Filters/Table/FilterTags.tsx
  frontend/src/features/Reportings/ReportingForm/AttachMission/AttachedMissionCard.tsx
  frontend/src/features/Reportings/ReportingsList/Cells/CellTarget.tsx
  frontend/src/features/Reportings/ReportingsList/Columns/index.tsx
  frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx
  frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
  frontend/src/features/Reportings/utils.test.ts
  frontend/src/features/Reportings/utils.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
Labels: feat. enhancement

#1140 [Unités] Améliorer recherche dans le module Unités de contrôle
  frontend/cypress/e2e/main_window/control_unit_list_dialog/filters.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/utils.tsx
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/FilterBar.tsx
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/types.ts
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/utils.ts
  frontend/src/features/ControlUnit/utils.ts
Labels: feat. enhancement

#1143 [Tech] Augmente le nombre de jobs Cypress dans la CI
  .github/workflows/cicd-app.yml
Labels: tech. enhancement

#1132 [Tech] Add lint warning for nullish coalescing operator enforcement
  frontend/.eslintrc.js
Labels: tech. enhancement

#1144 [Mission] Afficher les unités et administrations dans le formulaire de mission même si elles ont été archivées
  backend/src/main/resources/db/testdata/V666.06__insert_dummy_administrations.sql
  backend/src/main/resources/db/testdata/V666.07__insert_dummy_control_units.sql
  backend/src/main/resources/db/testdata/V666.09__insert_dummy_missions.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitRepositoryITests.kt
  frontend/cypress/e2e/back_office/administration_table/filters.spec.ts
  frontend/cypress/e2e/back_office/control_unit_table/filters.spec.ts
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/src/features/Reportings/ReportingForm/AttachMission/AttachedMissionCard.tsx
  frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx
  frontend/src/features/Reportings/utils.tsx
  frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
Labels: bug

#1133 [Unités] Fixe et améliore plusieurs points
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CanDeleteControlUnit.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/DeleteControlUnit.kt
  backend/src/main/resources/db/testdata/V666.09__insert_dummy_missions.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CanDeleteControlUnitUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/DeleteControlUnitUTests.kt
  frontend/cypress/e2e/back_office/control_unit_table/row_actions.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/administrationsAPI.ts
  frontend/src/api/controlUnitResourcesAPI.ts
  frontend/src/api/controlUnitsAPI.ts
  frontend/src/api/stationsAPI.ts
  frontend/src/domain/shared_slices/Global.ts
  frontend/src/domain/use_cases/reporting/addReporting.ts
  frontend/src/domain/use_cases/reporting/closeReporting.ts
  frontend/src/domain/use_cases/reporting/createMissionFromReporting.ts
  frontend/src/domain/use_cases/reporting/deleteReporting.ts
  frontend/src/domain/use_cases/reporting/deleteReportings.ts
  frontend/src/domain/use_cases/reporting/duplicateReporting.ts
  frontend/src/domain/use_cases/reporting/editReportingInLocalStore.ts
  frontend/src/domain/use_cases/reporting/reduceOrCollapseReportingForm.ts
  frontend/src/domain/use_cases/reporting/reduceReportingFormOnMap.ts
  frontend/src/domain/use_cases/reporting/saveReporting.ts
  frontend/src/domain/use_cases/reporting/switchReporting.ts
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Placeholder.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/utils.tsx
  frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/Item.tsx
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/utils.ts
  frontend/src/features/ControlUnit/utils.ts
  frontend/src/features/LocateOnMap/index.tsx
  frontend/src/features/MainWindow/components/RightMenu/ButtonWrapper.tsx
  frontend/src/features/MainWindow/components/RightMenu/ControlUnitListButton.tsx
  frontend/src/features/MainWindow/slice.ts
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/ReportingForm/index.tsx
  frontend/src/features/Reportings/index.tsx
  frontend/src/features/Reportings/style.ts
  frontend/src/features/SideWindow/SideWindowLauncher.tsx
  frontend/src/features/Station/components/StationLayer/index.ts
  frontend/src/features/Station/components/StationLayer/utils.ts
  frontend/src/features/map/shared/RightMenuOnHoverArea.tsx
Labels: bug, feat. enhancement

#1152 [Data] Mise à jour des tables servant à l'analyse de données avec les nouvelles thématiques
  backend/src/main/resources/db/migration/internal/V0.112__update_analytics_views_with_new_themes.sql
  backend/src/main/resources/db/migration/internal/V0.113__update_control_locations_view.sql
  datascience/tests/test_analytics_views/test_analytics_controls_locations_view.py
  datascience/tests/test_data/remote_database/V666.2__Reset_test_missions.sql
  datascience/tests/test_data/remote_database/V666.3__insert_dummy_env_actions.sql
  datascience/tests/test_pipeline/test_flows/test_refresh_materialized_views.py
Labels: bug

#1157 [Mission] Gestion du "multi-unité" dans une mission pour l'affichage du warning d'unité déjà en cours de mission
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/src/features/map/overlays/missions/MissionCard.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitWarningMessage.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm/index.tsx
Labels: feat. enhancement
