Repository MTES-MCT/monitorenv, pull requests merged in 2024-05, with the labels that each got.

#1330 [Signalement] Mise en place de l'enregistrement automatique des signalements
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/reporting/ReportingEntity.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/CreateOrUpdateReportingDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/reportings/ReportingDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt
  backend/src/main/resources/db/migration/internal/V0.125__add_updated_column_in_reportings.sql
  backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateReportingUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/.env.example
  frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts
  frontend/cypress/e2e/side_window/mission_form/delete_mission.spec.ts
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/cypress/e2e/side_window/mission_list/filters.spec.ts
  frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts
  frontend/cypress/e2e/side_window/reporting/reportings.spec.ts
  frontend/cypress/e2e/utils/createMissionWithAttachedReportingAndAttachedAction.ts
  frontend/cypress/e2e/utils/getMissionEndDate.ts
  frontend/cypress/e2e/utils/getUtcDateInMultipleFormats.ts
  frontend/cypress/e2e/utils/visitSideWindow.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/shared_slices/reporting.ts
  frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts
  frontend/src/domain/use_cases/reporting/duplicateReporting.ts
  frontend/src/domain/use_cases/reporting/saveReporting.ts
  frontend/src/domain/use_cases/reporting/unattachMissionFromReporting.ts
  frontend/src/env.d.ts
  frontend/src/features/Reportings/ReportingForm/AttachMission/AttachMissionToReportingModal.tsx
  frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Dialog/CancelEditDialog.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Footer.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Position/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Source.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/ReportingForm/Header.tsx
  frontend/src/features/Reportings/ReportingForm/Schema/index.tsx
  frontend/src/features/Reportings/ReportingForm/constants.ts
  frontend/src/features/Reportings/ReportingForm/index.tsx
  frontend/src/features/Reportings/ReportingsList/Cells/CellValidityTime.tsx
  frontend/src/features/Reportings/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/features/Reportings/style.ts
  frontend/src/features/Reportings/utils.tsx
  frontend/src/features/commonComponents/AutoSaveTag.tsx
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/Validity.tsx
  frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx
  infra/docker/docker-compose.prod.yml
  infra/docker/docker-compose.test.yml
Labels: new feature

#1358 [Mission] Résolution du bug de recalcul de la zone de mission
  backend/src/main/resources/db/testdata/V666.09__insert_dummy_missions.sql
  frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/cypress/e2e/side_window/mission_form/mission_zone.spec.ts
  frontend/cypress/e2e/utils/createPendingMission.ts
  frontend/cypress/mappings/monitorfish/get-mission_actions.53.json
  frontend/src/domain/entities/missions.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/MultiPointPicker.tsx
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/SurveillanceZonePicker.tsx
  frontend/src/features/missions/MissionForm/ActionsTimeLine/ActionCard/style.ts
  frontend/src/features/missions/MissionForm/ActionsTimeLine/index.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/constants.ts
  frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/features/missions/MissionForm/hooks/useUpdateFreezedFormValues.ts
  frontend/src/features/missions/MissionForm/hooks/useUpdateMissionZone.ts
  frontend/src/features/missions/MissionForm/utils.ts
  frontend/src/features/missions/Missions.helpers.ts
Labels: bug

#1360 [Reporting] Fix migration d'ajout de date de modification d'un signalement
  backend/src/main/resources/db/migration/internal/V0.126__add_updated_column_in_reportings.sql
  frontend/src/api/missionsAPI.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
Labels: bug

#1366 Revert "[Tech] Bump org.springframework.boot:spring-boot-starter-data-jpa from 3.1.4 to 3.2.5 in /backend"
  backend/build.gradle.kts
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitResourceModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/EnvActionModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
Labels: bug

#1367 [Mission] Le trigramme "complété par" des actions n'est plus obligatoire
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/src/domain/use_cases/missions/saveMission.ts
  frontend/src/features/missions/MissionForm/Schemas/Control.ts
  frontend/src/features/missions/MissionForm/Schemas/Surveillance.ts
Labels: feat. enhancement

#1372 [Mission] Pouvoir sauvegarder une mission même si des champs sont manquants
  frontend/cypress/e2e/side_window/mission_form/mission_zone.spec.ts
  frontend/src/domain/entities/missions.ts
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx
  frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/index.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/Schemas/index.ts
  frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/Missions.helpers.ts
Labels: bug

#1377 [Mission] Pouvoir sauvegarder une mission terminée même si des champs sont manquants
  frontend/cypress/e2e/utils/createMissionWithAttachedReportingAndAttachedAction.ts
  frontend/src/features/missions/MissionForm/CancelEditModal.tsx
  frontend/src/features/missions/MissionForm/CloseEditModal.tsx
  frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/MissionForm/utils.ts
Labels: bug

#1342 [Signalement] Mise en place de la mise à jour automatique des signalements
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/CreateOrUpdateReporting.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/events/UpdateReportingEvent.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/reportings/Reportings.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/reportings/SSEReporting.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateReportingUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsITests.kt
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/puppeteer/e2e/reportings.spec.ts
  frontend/puppeteer/setup.ts
  frontend/src/App.tsx
  frontend/src/context/mission/MissionEventContext.tsx
  frontend/src/context/mission/useMissionEventContext.ts
  frontend/src/context/reporting/ReportingEventContext.tsx
  frontend/src/context/reporting/useReportingEventContext.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/shared_slices/reporting.ts
  frontend/src/domain/use_cases/reporting/saveReporting.ts
  frontend/src/env.d.ts
  frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/ReportingForm/FormikSyncReportingFields.tsx
  frontend/src/features/Reportings/ReportingForm/constants.ts
  frontend/src/features/Reportings/ReportingForm/hooks/useListenReportingEventUpdates.ts
  frontend/src/features/Reportings/ReportingForm/sse.ts
  frontend/src/features/Reportings/ReportingForm/utils.ts
  frontend/src/features/Reportings/ReportingsButton/SearchReportings.tsx
  frontend/src/features/Reportings/utils.tsx
  frontend/src/features/SideWindow/index.tsx
  frontend/src/features/map/overlays/reportings/ReportingCard.tsx
  frontend/src/features/missions/MissionForm/FormikSyncMissionFields.tsx
  frontend/src/features/missions/MissionForm/MissionForm.tsx
  frontend/src/features/missions/MissionForm/hooks/useListenMissionEventUpdates.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/utils/isArray.ts
  frontend/src/utils/isObject.ts
  frontend/src/utils/undefinedize.ts
  infra/docker/docker-compose.prod.yml
  infra/docker/docker-compose.test.yml
Labels: new feature

#1389 [Tech] Suppression des propriétés `closedBy` et `isClosed`
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/CreateOrUpdateMissionDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionDataOutput.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiLegacyMissionsITests.kt
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/src/features/missions/MissionForm/constants.ts
Labels: tech. enhancement

#1371 [Carte] Amélioration de la pop-up pour dessiner une zone ou un point
  frontend/src/domain/use_cases/map/updateMapInteractionListeners.ts
  frontend/src/domain/use_cases/reporting/reduceOrCollapseReportingForm.ts
  frontend/src/features/Reportings/ReportingForm/FormComponents/Position/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/commonComponents/Modals/MapInteraction.tsx
  frontend/src/features/map/draw/DrawModal.tsx
  frontend/src/features/map/layers/InterestPointLayer.tsx
  frontend/src/features/map/overlays/InterestPointOverlay.tsx
  frontend/src/hooks/usePrevious.ts
Labels: feat. enhancement

#1397 [Points d'intérêt] – Supprimer les types de points, pouvoir masquer les points sur la carte, changer l'icone
  frontend/.env.example
  frontend/cypress/e2e/back_office/administration_form.spec.ts
  frontend/cypress/e2e/back_office/control_unit_form.spec.ts
  frontend/cypress/e2e/back_office/station_form.spec.ts
  frontend/cypress/e2e/main_window/interest_point.spec.ts
  frontend/cypress/e2e/side_window/mission_form/delete_mission.spec.ts
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/cypress/e2e/side_window/mission_list/filters.spec.ts
  frontend/cypress/e2e/side_window/reporting/filters.spec.ts
  frontend/cypress/e2e/utils/dates.test.ts
  frontend/cypress/e2e/utils/dates.ts
  frontend/cypress/e2e/utils/getMissionEndDate.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Point_interet_feature_autre.png
  frontend/public/Point_interet_feature_engin.png
  frontend/public/Point_interet_feature_moyen.png
  frontend/public/Point_interet_feature_navire.png
  frontend/public/interest_point.svg
  frontend/src/domain/entities/interestPointLine.ts
  frontend/src/domain/entities/interestPoints.ts
  frontend/src/domain/shared_slices/Global.ts
  frontend/src/domain/shared_slices/InterestPoint.ts
  frontend/src/features/InterestPoint/types.ts
  frontend/src/features/coordinates/DDCoordinatesInput.tsx
  frontend/src/features/coordinates/DMDCoordinatesInput.tsx
  frontend/src/features/coordinates/DMSCoordinatesInput.tsx
  frontend/src/features/coordinates/SetCoordinates.tsx
  frontend/src/features/map/BaseMap.tsx
  frontend/src/features/map/controls/MapCoordinatesBox.tsx
  frontend/src/features/map/layers/InterestPointLayer.tsx
  frontend/src/features/map/layers/Missions/SelectedMissionLayer.ts
  frontend/src/features/map/layers/styles/interestPoint.style.ts
  frontend/src/features/map/overlays/InterestPointOverlay.tsx
  frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
  frontend/src/features/map/tools/interestPoint/EditInterestPoint.tsx
  frontend/src/features/map/tools/interestPoint/InterestPointMapButton.tsx
  frontend/src/features/map/tools/measurements/CustomCircleRange.tsx
Labels: feat. enhancement

#1409 [Test] fix tests e2e
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
Labels: bug

#1408 [Design] Améliorations UI
  frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
  frontend/src/features/LocateOnMap/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormikSyncReportingFields.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionsForm.tsx
  frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx
  frontend/src/features/missions/MissionForm/FormikSyncMissionFields.tsx
  frontend/src/features/missions/MissionForm/index.tsx
  frontend/src/features/missions/MissionsList/CellActionThemes.tsx
Labels: feat. enhancement, UI

#1403 [Unité de contrôle] La modal d'édition d'une unité s'adapte en hauteur au contenu
  frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx
  frontend/src/features/Station/components/StationLayer/utils.ts
Labels: feat. enhancement, UI

#1384 [Thématiques] Ajouter une possibilité de recherche dans le menu des filtres "thématique réglementaire"
  frontend/src/features/layersSelector/myAmps/MyAMPLayerGroup.tsx
  frontend/src/features/layersSelector/search/LayerFilters.tsx
  frontend/src/features/layersSelector/search/SearchInput.tsx
  frontend/src/features/layersSelector/utils/LayerSelector.style.ts
Labels: feat. enhancement

#1396 [Contrôle] Mettre à jour les informations d'un contrôle lorsqu'on change le signalement rattaché à cette action
  frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts
  frontend/cypress/e2e/utils/createReportingOnSideWindow.ts
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx
  frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx
  frontend/src/features/missions/MissionForm/Schemas/Control.ts
  frontend/src/features/missions/MissionForm/Schemas/Infraction.ts
Labels: feat. enhancement

#1410 [Signalement] Ajout d'un champ "avéré/ non avéré" dans le formulaire de signalement
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/reporting/ReportingEntity.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/CreateOrUpdateReportingDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/reportings/ReportingDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/reportings/ReportingsDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt
  backend/src/main/resources/db/migration/internal/V0.131__update_reportings_table.sql
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateReportingUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CanDeleteControlUnitUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/DeleteMissionUTests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/TestUtils.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/ReportingsITests.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/src/domain/entities/reporting.ts
  frontend/src/domain/shared_slices/ReportingsFilters.ts
  frontend/src/features/Reportings/Filters/index.tsx
  frontend/src/features/Reportings/ReportingForm/FormContent.tsx
  frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
  frontend/src/features/Reportings/style.ts
  frontend/src/features/Reportings/utils.tsx
  frontend/src/features/missions/MissionsList/Filters/index.tsx
  frontend/src/hooks/useGetFilteredMissionsQuery.ts
Labels: feat. enhancement
