Repository MTES-MCT/monitorenv, pull requests merged in 2025-01, with the labels that each got.

#1955 [Tableau de bord]: ne pas filtrer les tableaux quand il n'y a pas de date de mise à jour
  frontend/src/features/Dashboard/useCases/filters/filterByUpdatedAt.ts
Labels: bug

#1967 [Tech] Fix de bugs html
  frontend/src/components/Table/index.tsx
  frontend/src/features/Dashboard/components/DashboardsList/Filters.tsx
Labels: bug

#2026 [Tableau de bord] Ne pas préparer le téléchargement du brief à l'ouverture du tableau
  frontend/src/features/Dashboard/components/Pdf/v1/GeneratePdfButton.tsx
  frontend/src/features/Dashboard/components/Pdf/v2/GeneratePdfButton.tsx
Labels: bug

#2028 [Mission] Réinitialiser les filtres des unités de contrôle au moment du zoom
  frontend/src/features/ControlUnit/components/ControlUnitListDialog/slice.ts
  frontend/src/features/ControlUnit/useCases/centerOnStation.ts
  frontend/src/features/Mission/components/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx
Labels: bug

#2036 [Map] Ajout d'un contour clair sur les icônes de Sémaphore et de Tableau de bord sur la carte
  frontend/public/icons/Bullseye.svg
  frontend/public/icons/bullseye_border.svg
  frontend/public/icons/semaphore_border.svg
  frontend/public/icons/semaphore_border_highlighted.svg
  frontend/public/semaphore.svg
  frontend/src/features/Dashboard/components/Layers/DashboardsLayer.tsx
  frontend/src/features/Semaphore/components/Layer/style.ts
Labels: UI

#2029 [Tableau de bord & Brief] Résolution du bug d'affichage de la liste des AMP
  frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx
  frontend/src/features/Dashboard/components/DashboardForm/style.ts
Labels: bug, UI

#2043 [Signalements] Laisser les signalements affichés sur la carte lors du dessin d'un point ou d'une zone d'un signalement
  frontend/src/features/Mission/components/Layers/index.tsx
  frontend/src/features/Reportings/components/ReportingLayer/Reporting/index.tsx
Labels: feat. enhancement

#2038 [Zones administratives] Ajout de la zone de limite à 300 mètres pour La Réunion
  backend/src/main/resources/db/migration/layers/V0.169__create_three_hundred_meters_areas.sql
  datascience/src/pipeline/flows/three_hundred_meters_areas.py
  datascience/src/pipeline/flows_config.py
  datascience/src/pipeline/queries/cross/cacem/three_hundred_meters_areas.sql
  datascience/tests/test_data/cacem_database/V666.503__threee_hundred_meters_areas.sql
  datascience/tests/test_pipeline/test_flows/test_three_hundred_meters_areas.py
  frontend/src/domain/entities/administrativeLayers.ts
  frontend/src/domain/entities/layers/constants.ts
  frontend/src/features/map/layers/styles/administrativeAndRegulatoryLayers.style.ts
  infra/init/geoserver_init_layers.sh
  infra/init/postgis_insert_layers.sh
Labels: new feature

#2056 [Zones de vigilance] Ajout d'un bouton dans la section "Mes zones de vigilances" pour aller sur la vue liste
  frontend/src/features/layersSelector/myVigilanceAreas/index.tsx
Labels: feat. enhancement

#2053 [Bases] Mise à jour de l'icone des bases pour ajouter un contour blanc
  frontend/public/icons/station-layer-icon-highlighted.svg
  frontend/public/icons/station-layer-icon.svg
  frontend/public/icons/station_border.svg
  frontend/public/icons/station_border_highlighted.svg
  frontend/src/features/Station/components/StationLayer/utils.ts
Labels: feat. enhancement

#2052 [Signalement] Ne rendre accessible le bouton d'archivage que si le signalement est valide
  backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql
  frontend/cypress/e2e/side_window/reporting/reportings.spec.ts
  frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx
  frontend/src/features/Reportings/components/ReportingsList/Cells/ButtonsRowGroup.tsx
  frontend/src/features/Reportings/useCases/archiveReporting.ts
Labels: bug
