Repository MTES-MCT/monitorenv, pull requests merged in 2025-03, with the labels that each got.

#2158 [Mission] Vider le champ Type de véhicule lors de la mise à jour du champ Type de cible
  frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
  frontend/src/features/Mission/components/MissionForm/ActionForm/ControlForm/index.tsx
Labels: bug

#2164 tech: Montée de version de la JVM et nettoyage de dépendences
  backend/build.gradle.kts
  backend/gradle/wrapper/gradle-wrapper.properties
  infra/docker/app/Dockerfile
Labels: tech. enhancement

#2160 [RAPPORT NAV] Ajouter les observations de l'unité dans l'API publique de récupération de mission
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/CreateOrUpdateMissionDataInput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionWithRapportNavActionsDataOutput.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v1/missions/LegacyMissionsITests.kt
Labels: RapportNav

#2181 [Brief]: Refonte technique du téléchargement du brief et de la récupération d'images
  frontend/src/domain/entities/layers/constants.ts
  frontend/src/features/Dashboard/components/Pdf/v1/GeneratePdfButton.tsx
  frontend/src/features/Dashboard/components/Pdf/v2/GeneratePdfButton.tsx
  frontend/src/features/Dashboard/hooks/useExportImages.tsx
Labels: tech. enhancement

#2193 [Activité Récente] Améliorations UI
  frontend/public/icons/dot.svg
  frontend/src/features/RecentActivity/components/RecentActivityLegend.tsx
  frontend/src/features/RecentActivity/components/RecentActivityMenuButton/index.tsx
  frontend/src/features/map/index.tsx
Labels: feat. enhancement

#2199 [Tech] Mise à jour des données test des Zones de vigilance
  backend/src/main/resources/db/testdata/V666.15__insert_dummy_vigilance_area.sql
  frontend/cypress/e2e/main_window/vigilance_area/edit_vigilance_area.spec.ts
Labels: bug
