Repository MTES-MCT/monitorenv, pull requests merged in 2025-07, with the labels that each got.

#2434 [Tech]:Ajout d'une limite dans la récupération des missions et des signalements
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt
Labels: tech. enhancement

#2423 [Signalement] Ajout d'un bouton pour copier dans la presse-papier les informations du signalement
  frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx
Labels: new feature

#2459 [Zone de vigilance] Désarchivage des zones de vigilances
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceArea.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceAreaUTests.kt
Labels: feat. enhancement, Zone de vigilance
