Repository MTES-MCT/monitorenv, pull requests merged in 2025-08, with the labels that each got.

#2467 [Zone de vigilance] Ne pas afficher le bouton de revalidation dans la vue du Tableau de bord
  frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Panel/index.tsx
  frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Panel/PanelDates.tsx
  frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Panel/ValidateAt.tsx
Labels: bug

#2479 [Tableau de bord] Supprimer les données enregistrées d'un tableau de bord lors de sa suppression
  backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaDashboardRepository.kt
  backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaDashboardRepositoryITests.kt
Labels: tech. enhancement

#2328 [Unité de contrôle] Remplacer le terme "Piéton" par "Pédestre" dans les moyens des unités de contrôle
  backend/src/main/resources/db/migration/internal/V0.184__add_pedetrian_resource_on_control_units.sql
Labels: feat. enhancement

#2487 [Tableau de bord] Correction sur l'affichage de l'overlay
  frontend/src/features/Dashboard/components/Layers/DashboardsLayer.tsx
  frontend/src/features/Dashboard/components/Overlays/DashboardOverlay.tsx
Labels: bug
